name: carnd-advdl-odlab
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6.1
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scipy
    - ffmpeg
    - imageio==2.5.0
    - pip:
        - moviepy
        - tensorflow==1.4
